version: "3"

services:
    db:
        image: mongo:4.4
        container_name: blog-mongodb
        restart: always
        environment:
            - MONGO_HOST=db
            - MONGO_DB=blog-mongodb
    app: 
        build: .
        container_name: blog-api
        restart: always
        depends_on:
            - "db"
        ports: 
            - "3100:3100"